### ISSUE TITLE
Reference permission request

### ISSUE THREAD

**Issue by longlin10086** [Doctxing/phytex#1]
同学你好！
我是 [HITSZ-OpenAuto](https://github.com/HITSZ-OpenAuto) 项目的负责人之一。我在 GitHub 上看到了你的项目，现在想在 hoa.moe 的 [大物实验页面](https://hoa.moe/docs/fresh-spring/phys1002/) 对这个仓库进行链接引用，不知可否？非常感谢你对开源所做的贡献，希望这样能帮助到更多同学。

**Comment by Doctxing** [comment]
okok没有问题

**Comment by Doctxing** [comment]
OK
