### ISSUE TITLE
A formula typo in RLC.tex

### ISSUE THREAD

**Issue by longlin10086** [Doctxing/phytex#2]
在 数据处理 部分的 第二小问中，学校所给出的公式为 

 $$ \ln\left( 1 - \frac{U_C}{E}\right) \sim t $$

此处笔误为

$$  \ln\left(\frac{U_C}{E}-1\right) \sim t $$

**Comment by Doctxing** [comment]
并非笔误，因计算方法不同，在思考后进行了改正，是刻意为之的

**Comment by Doctxing** [comment]
我微分方程应当没解错吧（，不管怎样我这样来算的计算结果比较切合理论值。
